{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    {{- include "django-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
